/*
 * File: app/model/Archive.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('app.model.Archive', {
    extend: 'Ext.data.Model',
    config: {
        fields: [
            {
                name: 'id'
            },
            {
                name: 'channel_id'
            },
            {
                name: 'title',
                type: 'string'
            },
            {
                name: 'thumbnail',
                type: 'string'
            },
            {
                name: 'urlhq',
                type: 'string'
            },
            {
                name: 'urllq',
                type: 'string'
            },
            {
                name: 'synopsis',
                type: 'string'
            },
            {
                name: 'poster',
                type: 'string'
            }
        ],
        proxy: {
            type: 'jsonp',
            extraParams: '[channel_id]',
            url: 'http://192.168.1.114/techtv24/archives.php',
            reader: {
                type: 'json',
                rootProperty: 'archives'
            }
        }
    }
});