/*
 * File: app/model/Channel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Channels.model.Channel', {
    extend: 'Ext.data.Model',
    config: {
        fields: [
            {
                name: 'title',
                type: 'string'
            },
            {
                name: 'synopsis'
            },
            {
                mapping: 'thumbnail',
                name: 'thumbnail',
                type: 'string'
            },
            {
                mapping: 'poster',
                name: 'poster'
            },
            {
                mapping: 'rating',
                name: 'rating',
                type: 'int'
            },
            {
                mapping: 'url',
                name: 'url',
                type: 'string'
            },
            {
                mapping: 'urllq',
                name: 'urllq',
                type: 'string'
            }
        ],
        proxy: {
            type: 'jsonp',
            url: 'http://www.edtv24.com/edtv24.php',
            reader: {
                type: 'json',
                rootProperty: 'channels'
            }
        }
    }
});