/*
 * File: app/view/ChannelsDetails.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Channels.view.ChannelsDetails', {
    extend: 'Ext.Panel',
    alias: 'widget.channelsdetails',

    config: {
        scrollable: 'vertical',
        cls: [
            'channelDetails'
        ],
        tpl: [
            '<div class="poster"><img src="data:image/jpeg;base64,{poster}"></div>',
            '',
            '<p class="synopsis">{synopsis}</p>',
            '',
            '<div class="url">',
            '<a href="{url}" align=middle>View High Bitrate Channnel</a>',
            '',
            '</div>',
            '<div class="urllq">',
            '<a href="{urllq}" align=middle>View Low Bitrate Channnel</a>',
            '</div>'
        ]
    }

});