//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OvsControl.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDS_ABOUTBOX                    101
#define IDS_CAPTION                     102
#define IDS_CAPTION_IDC_BUTTON_EDIT_VID_INPUT 103
#define IDS_TTIP_EDIT_VID_INPUT         104
#define IDS_TTIP_RESET_VID_LIST         105
#define IDS_TTIP_SLIDER_GREEN_CONTRAST  106
#define IDD_PAGE_INPUT_VIDEOS           107
#define IDS_TTIP_SLIDER_GREEN_BRIGHT    107
#define IDD_PAGE_SKYPE                  108
#define IDS_TTIP_UPDATE_VID_LIST        108
#define IDD_PAGE_RECORD                 109
#define IDS_TTIP_UPSIDEDOWN             109
#define IDD_PAGE_PUBLISH                110
#define IDS_TTIP_ROTATION               110
#define IDD_PAGE_HOME                   111
#define IDS_TTP__IMG_PLANE              111
#define IDS_TTIP_COLORKEYENABLE         112
#define IDD_ABOUTBOX                    113
#define IDS_TTIP_AUTO_REPLY             113
#define IDD_DIALOG_EDIT_CAMERA          114
#define IDS_TTIP_SKYPE_HANGUP           114
#define IDD_DIALOG_EDIT_SKYPE           115
#define IDS_TTIP_SKYPE_CALL             115
#define IDD_DIALOG_EDIT_RTSP            116
#define IDS_TTIP_LOGOUT                 116
#define IDS_TTIP_LOGIN                  117
#define IDD_DIALOG_CONFIG_SKYPE         117
#define IDS_TTIP_VIDEO_IN               118
#define IDD_PAGE_LIVECAST               118
#define IDS_TTIP_VIDEO_OUT              119
#define IDD_DIALOG_EDIT_RTMP            119
#define IDS_TTIP_RECORD                 120
#define IDD_DIALOG_EDIT_RTP_REC         120
#define IDS_TTIP_STOP                   121
#define IDD_PAGE_LAYOUT                 121
#define IDS_TTIP_PAUSE                  122
#define IDD_PAGE_LAYOUT1                122
#define IDD_DIALOG_EDIT_UDP             122
#define IDS_TTIP_RESUME                 123
#define IDD_DIALOG_EDIT_HLS             123
#define IDS_TTIP_INPUT_SOURCE           124
#define IDD_DIALOG_EDIT_RTSP_SRV        124
#define IDS_TTIP_SKYPE_CONFIG           125
#define IDD_HLS_PUBLISH_S3              125
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       131
#define IDC_3D_ENTITY                   131
#define IDR_DIALOG_MENU                 132
#define IDB_IMAGE                       137
#define IDR_TOOLBAR_MENU_IMAGES         141
#define IDB_ICONS                       143
#define IDB_PROPICONS                   147
#define IDB_BUTTONS                     149
#define IDB_CHECKNO                     151
#define IDB_ICONS32                     159
#define IDB_BITMAP_DISPLAY1             161
#define IDB_BITMAP_DISPLAY2             163
#define IDB_BITMAP_DISPLAY3             164
#define IDB_BITMAP_ANCHOR1              165
#define IDB_BITMAP_ANCHOR2              166
#define IDB_BITMAP_OVERLAY1             167
#define IDB_BITMAP_WELCOME              168
#define IDI_ICON1                       169
#define IDB_BITMAP_DISPLAY0             177
#define IDB_BITMAP_GEN_ENABLE           178
#define IDB_BITMAP_GEN_DISABLE          179
#define IDB_BITMAP_SKYPE_IMG_16X16      180
#define IDB_BITMAP_SKYPE_IMG_32X32      181
#define IDB_BITMAP_LED_ON               182
#define IDB_BITMAP_LED_OFF              183
#define IDB_BITMAP_ARROW_DN             184
#define IDB_BITMAP_ARROW_UP             185
#define IDB_BITMAP_CAMERASRC            187
#define IDB_BITMAP_FILESRC              188
#define IDB_BITMAP_IPCAMSRC             189
#define IDB_BITMAP_SKYPESRC             190
#define IDB_BITMAP_NOSRC                191
#define IDB_BITMAP_ARROW_LEFT           192
#define IDB_BITMAP_ARROW_RIGHT          193
#define IDB_BITMAP_CAMERASRC_SML        194
#define IDB_BITMAP_SKYPESRC_SML         195
#define IDB_BITMAP_FILESRC_SML          196
#define IDB_BITMAP_NOSRC_SML            197
#define IDB_BITMAP6                     198
#define IDB_BITMAP_IPCAMSRC_SML         198
#define IDB_BITMAP_PHONEACCEPT          199
#define IDB_BITMAP_PHONEACCEPTU         199
#define IDB_BITMAP_PHONEREJECT          200
#define IDB_BITMAP_PHONEREJECTU         200
#define IDB_BITMAP_MP4U                 201
#define IDB_BITMAP_HLSU                 202
#define IDB_BITMAP_RESETU               203
#define RECORDD                         204
#define RECORDU                         205
#define RECORDF                         206
#define RECORDX                         207
#define STOPD                           208
#define STOPU                           209
#define STOPX                           210
#define PAUSED                          211
#define PAUSEU                          212
#define PAUSEX                          213
#define RESUMED                         214
#define RESUMEU                         215
#define RESUMEX                         216
#define IDB_BITMAP_RESETD               217
#define IDB_BITMAP2                     218
#define IDB_BITMAP_RESETX               218
#define IDB_BITMAP_ITEMEDITU            220
#define IDB_BITMAP_ITEMEDITD            221
#define IDB_BITMAP_ITEMEDITX            222
#define IDB_BITMAP_RETURNLISTU          223
#define IDB_BITMAP_RETURNLISTD          225
#define IDB_BITMAP_RETURNLISTX          226
#define IDB_BITMAP_PHONEREJECTD         227
#define IDB_BITMAP_PHONEACCEPTD         229
#define IDB_BITMAP_LOGINU               230
#define IDB_BITMAP_LOGIND               231
#define IDB_BITMAP_LOGINX               232
#define IDB_BITMAP_LOGOUTU              233
#define IDB_BITMAP_LOGOUTD              234
#define IDB_BITMAP_LOGOUTX              235
#define IDB_BITMAP_AUDCFGU              236
#define IDB_BITMAP_AUDCFGD              237
#define IDB_BITMAP_AUDCFGX              239
#define IDB_BITMAP_GEN_DISABLEU         240
#define IDB_BITMAP_GEN_DISABLED         241
#define IDB_BITMAP_GEN_ENABLEU          242
#define IDB_BITMAP1_GEN_ENABLED         243
#define IDB_BITMAP_GEN_ENABLED          243
#define IDB_TAB_ICON_MIXER              251
#define IDB_TAB_ICON_SKYPE              252
#define IDB_TAB_ICON_LIVECAST           253
#define IDB_TAB_ICON_RECORD             254
#define IDB_TAB_ICON_LAYOUT             258
#define IDC_BUTTON                      1000
#define IDC_SLIDER_GREEN_BRIGHT         1001
#define IDC_SLIDER_GREEN_CONTRAST       1002
#define IDC_BUTTON_UPDATE_VID_LIST      1003
#define IDC_BUTTON_COLORKEYENABLE       1005
#define IDC_BUTTON_UPSIDEDOWN           1006
#define IDC_BUTTON_EDIT_VID_INPUT       1007
#define IDC_BUTTON_RESET_VID_LIST       1008
#define IDC_COMBO_ROTATION_SELECTION    1009
#define IDC_EDIT_STREAM_PATH            1010
#define IDC_LIST_INPUT_STREAMS          1011
#define IDC_UPLOAD_PROGRESS2            1012
#define IDC_EDIT_S3_HOST_NAME           1013
#define IDC_EDIT_S3_ACCESS_ID           1014
#define IDC_EDIT_S3_SECURITY_KEY        1015
#define IDC_EDIT_S3_BUCKET              1016
#define IDC_EDIT_S3_FOLDER              1017
#define IDC_EDIT_LOCAL_FOLDER           1018
#define IDC_EDIT_STREAM                 1018
#define IDC_EDIT_STATUS                 1019
#define IDC_BUTTON_BROWSE_FOLDER        1020
#define IDC_UPLOAD_PROGRESS1            1021
#define IDC_BUTTON_START_UPLOAD         1023
#define IDC_BUTTON_CANCEL_UPLOAD        1024
#define IDC_BUTTON_CLEAR_CHANNEL        1025
#define IDC_BUTON_RESUME                1026
#define IDC_BUTON_PAUSE                 1027
#define IDC_BUTTON_LAUNCH_ONYX          1060
#define IDC_BUTTON_NEXT                 1060
#define IDC_BUTTON_PREV                 1061
#define IDC_BUTON_STOP                  1063
#define IDC_WELCOME_SLIDES              1064
#define IDC_COMBO_AUDIO_INPUT           1121
#define IDC_COMBO_VIDEO_INPUT           1122
#define IDC_EDIT_RTSP_ADDR              1123
#define IDC_EDIT_BITRATE                1124
#define IDC_EDIT_VID_BITRATE            1124
#define IDC_EDIT_RTPREC_USER_ID         1124
#define IDC_EDIT_PORT                   1124
#define IDC_EDIT_GOP_LENGTH             1125
#define IDC_EDIT_RTPREC_HOST_PORT       1125
#define IDC_EDIT_PORT2                  1125
#define IDC_EDIT_AUD_BITRATE            1126
#define IDC_EDIT_RTPREC_PASSWD          1126
#define IDC_EDIT_FILE_NAME              1128
#define IDC_BUTON_RECORD                1129
#define IDC_EDIT_RTPREC_STREAM_NAME     1130
#define IDC_BUTTON_BROWSE_OUT           1131
#define IDC_EDIT_SKYPE_ID               1132
#define IDC_EDIT_PASSWD                 1133
#define IDC_BUTTON_LOGIN                1134
#define IDC_BUTTON_LOGOUT               1135
#define IDC_BUTTON_SKYPE_CONFIG         1137
#define IDC_AUTO_REPLY                  1138
#define IDC_EDIT_SKYPE_STATUS           1151
#define IDC_LIST_SKYPE_CONTACTS         1156
#define IDC_EDIT_CONTACT                1158
#define IDC_BUTTON_SKYPE_CALL           1159
#define IDC_BUTTON_SKYPE_HANGUP         1162
#define IDC_BUTTON_ADD_AUTOREPLY        1165
#define IDC_BUTTON_DEL_AUTOREPLY        1166
#define IDC_EDIT_AUTO_REPLY             1168
#define IDC_STATIC_VIDEO_IN             1170
#define IDC_STATIC_VIDEO_OUT            1171
#define IDC_STATIC_CONTACTLIST          1172
#define IDC_STATIC_LABLE_VID_IN         1173
#define IDC_STATIC_LABLE_VID_OUT        1174
#define IDC_STATIC_STATUS               1175
#define IDC_STATIC_ACCOUNT              1176
#define IDC_STATIC_PASSWD               1177
#define IDC_STATIC_LABEL_AUTO_REPLY     1178
#define IDC_STATIC_LABLE_CONTACT        1179
#define IDC_STATIC_LABEL_VIDEOLANE_LIST 1180
#define IDC_STATIC_LABLE_SOURCE_LOCATION 1181
#define IDC_STATIC_LABEL_VIDEO_PLANE    1182
#define IDC_STATIC_LABLE_SOURCE_TYPE    1183
#define IDC_COMBO_SELECT_CAMERA         1188
#define IDC_STATIC_IMG_PLANE            1190
#define IDC_STATIC_OPTIONS              1191
#define IDC_EDIT_RECORD_STATUS          1195
#define IDC_COMBO1                      1196
#define IDC_COMBOEX_ROTATION            1196
#define IDC_COMBO_SKYPE_AUDIO_INPUT     1196
#define IDC_COMBO_VIEW                  1196
#define IDC_COMBOEX_ROTATION2           1197
#define IDC_COMBOEX_INPUT_SOURCE        1197
#define IDC_COMBO_SKYPE_AUDIO_OUTPUT    1197
#define IDC_EDIT2                       1199
#define IDC_EDIT1                       1200
#define IDC_EDIT_SKYPE_VIDEO_CHANNEL    1200
#define IDC_EDIT_VIEW_NAME              1200
#define IDC_BUTTON_SET_DEFAULTS         1201
#define IDC_SLIDER_AUD_BITRATE          1202
#define IDC_CHECK_SERVER1_RECORD        1202
#define IDC_SLIDER_VID_BITRATE          1203
#define IDC_EDIT_RTPREC_HOST_ADDR       1203
#define IDC_CHECK_SERVER1_RECORD2       1203
#define IDC_CHECK_SERVER2_RECORD        1203
#define IDC_SLIDER_GOPLENGTH            1204
#define IDC_EDIT_RTMP_ADDR              1204
#define IDC_BUTTON_CONFIGURE            1205
#define IDC_EDIT_RTMP_ADDR_BACKUP       1205
#define IDC_COMBO_LAYOUT                1207
#define IDC_COMBO_WALLPAPER             1208
#define IDC_SLIDER_SCENE_ZOOM           1209
#define IDC_SLIDER_SCENE_MOVE_HORZ      1210
#define IDC_SLIDER_SCENE_MOVE_VERT      1211
#define IDC_SLIDER_SCENE_ROTATE_VERT    1212
#define IDC_SLIDER_SCENE_ROTATE_HORZ    1213
#define IDC_SLIDER_ANCHOR_ZOOM          1214
#define IDC_SLIDER_ANCHOR_MOVE_VERT     1215
#define IDC_SLIDER_ANCHOR_MOVE_HORZ     1216
#define IDC_SLIDER_ANCHOR_ROTATE_VERT   1217
#define IDC_SLIDER_ANCHOR_MOVE_FRONT    1218
#define IDC_BUTTON1                     1219
#define IDC_BUTTON_VIEW_SAVE            1219
#define IDC_BUTTON_VIEW_CLEAR           1220
#define IDC_CHECK_ANCHOR_LOCK           1220
#define IDC_BUTTON_VIEW_REFRESH         1221
#define IDC_SLIDER_CROP_LEFT            1221
#define IDC_CHECK_ANCHOR_HIDE           1222
#define IDC_SLIDER_CROP_TOP             1222
#define IDC_SLIDER_CROP_RIGHT           1223
#define IDC_CHECK_STITCH_PLANES         1223
#define IDC_SLIDER_CROP_BOTTOM          1224
#define IDC_EDIT_ADDR                   1229
#define IDC_COMBOEX_DEST_FORMAT         1230
#define IDC_EDIT_FOLDER                 1232
#define IDC_EDIT_HOST_NAME              1233
#define IDC_EDIT_SRV_ROOT               1233
#define IDC_EDIT_SECURITY_KEY           1234
#define IDC_EDIT_ACCESS_ID              1235
#define IDC_EDIT_SEGMENT_DURATION       1236
#define IDC_CHECK_LIVEONLY              1237
#define IDC_EDIT_BUCKET_NAME            1238
#define ID_ITEM_1                       32771
#define ID_ITEM_2                       32772
#define ID_ITEM_3                       32773
#define ID_ITEM_4                       32774
#define ID_DIALOG_ABOUT                 32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        259
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1239
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
